/* autogenerated by Processing revision 1278 on 2022-01-20 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class ThoughtworksAssignmentOOP extends PApplet {


class MovingCircle{
  private float circleXpos;
  private float circleYpos;
  private float circleXspeed;
  private float radius;
  
  public MovingCircle(float circleXpos,float circleXspeed,float circleYpos,float radius){
    this.circleXpos=circleXpos;
    this.circleXspeed=circleXspeed;
    this.circleYpos=circleYpos;
    this.radius=radius;
  }
  
  public void updateXpos()
  {
    circleXpos+=circleXspeed;
  }
  
  public void draw()
  {
    ellipse(circleXpos,circleYpos,radius,radius);
  }
  
}


MovingCircle movingCircle1,movingCircle2,movingCircle3,movingCircle4;

 public void setup(){
  /* size commented out by preprocessor */;
  movingCircle1=new MovingCircle(0,1,height/5,10);
  movingCircle2=new MovingCircle(0,2,2*height/5,10);
  movingCircle3=new MovingCircle(0,3,3*height/5,10);
  movingCircle4=new MovingCircle(0,4,4*height/5,10);
}

 public void draw()
{
  movingCircle1.draw();
  movingCircle1.updateXpos();
  movingCircle2.draw();
  movingCircle2.updateXpos();
  movingCircle3.draw();
  movingCircle3.updateXpos();
  movingCircle4.draw();
  movingCircle4.updateXpos();
  
}


  public void settings() { size(1080, 720); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "ThoughtworksAssignmentOOP" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
